baseURL = 'https://hhanh00.github.io/ywdocs/'
languageCode = 'en-us'
title = 'YWallet'
noChmod = true
[module]
[[module.imports]]
    path = 'github.com/McShelby/hugo-theme-relearn'
[security]
  [security.exec]
    allow = ['^(dart-)?sass(-embedded)?$', '^go$', '^npx$', '^postcss$', '^rst2html$']
[outputs]
  home = ['html', 'rss', 'search', 'searchpage']
